# Generated by Django 2.2.11 on 2020-03-13 01:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Niveis',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=254, verbose_name='Título')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Perguntas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=254, verbose_name='Título')),
                ('descricao', models.TextField(verbose_name='Descrição')),
                ('a', models.CharField(max_length=254, verbose_name='A')),
                ('b', models.CharField(max_length=254, verbose_name='B')),
                ('c', models.CharField(max_length=254, verbose_name='C')),
                ('d', models.CharField(max_length=254, verbose_name='D')),
                ('resposta', models.CharField(max_length=254, verbose_name='Resposta')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Simulados',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=254, verbose_name='Título')),
                ('descricao', models.TextField(verbose_name='Descricao')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('categorias', models.ManyToManyField(to='blog.Categorias')),
                ('nivel', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='simulados', to='questoes.Niveis')),
                ('perguntas', models.ManyToManyField(to='questoes.Perguntas')),
            ],
        ),
    ]
