# Generated by Django 2.2.11 on 2020-03-13 01:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('blog', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Topicos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=254, verbose_name='Título')),
                ('conteudo', models.TextField(verbose_name='Conteudo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('categorias', models.ManyToManyField(to='blog.Categorias')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='topicos', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Respostas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('conteudo', models.TextField(verbose_name='Conteudo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('topico', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='respostas', to='forum.Topicos')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='respostas', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
